<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\User;

class FloresVehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get a mitra user for vehicle assignment
        $mitra = User::where('role', 'mitra')->first();
        if (!$mitra) {
            $this->command->warn('No mitra user found. Please create a mitra user first.');
            return;
        }

        $vehicles = [
            // Mobil Kecil untuk perjalanan jarak pendek
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Toyota Agya',
                'plat_nomor' => 'EB 1234 AB',
                'jenis' => 'city_car',
                'vehicle_type' => 'Toyota Agya',
                'brand' => 'Toyota',
                'transmission' => 'manual',
                'capacity' => 4,
                'year' => 2022,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 350000,
                'harga_sewa_dengan_sopir_per_hari' => 500000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio', 'USB Charger']),
                'foto' => 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800',
            ],
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Daihatsu Ayla',
                'plat_nomor' => 'EB 2345 AB',
                'jenis' => 'city_car',
                'vehicle_type' => 'Daihatsu Ayla',
                'brand' => 'Daihatsu',
                'transmission' => 'manual',
                'capacity' => 4,
                'year' => 2021,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 350000,
                'harga_sewa_dengan_sopir_per_hari' => 500000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio']),
                'foto' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
            ],
            // MPV untuk keluarga dan travel
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Toyota Avanza',
                'plat_nomor' => 'EB 3456 AB',
                'jenis' => 'mpv',
                'vehicle_type' => 'Toyota Avanza',
                'brand' => 'Toyota',
                'transmission' => 'manual',
                'capacity' => 7,
                'year' => 2022,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 500000,
                'harga_sewa_dengan_sopir_per_hari' => 650000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio', 'USB Charger', 'Bagasi Luas']),
                'foto' => 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800',
            ],
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Daihatsu Xenia',
                'plat_nomor' => 'EB 4567 AB',
                'jenis' => 'mpv',
                'vehicle_type' => 'Daihatsu Xenia',
                'brand' => 'Daihatsu',
                'transmission' => 'manual',
                'capacity' => 7,
                'year' => 2021,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 450000,
                'harga_sewa_dengan_sopir_per_hari' => 600000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio', 'Bagasi']),
                'foto' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
            ],
            // MPV Premium untuk travel antar kota
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Toyota Innova Reborn',
                'plat_nomor' => 'EB 5678 AB',
                'jenis' => 'mpv_premium',
                'vehicle_type' => 'Toyota Innova Reborn',
                'brand' => 'Toyota',
                'transmission' => 'automatic',
                'capacity' => 7,
                'year' => 2023,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 800000,
                'harga_sewa_dengan_sopir_per_hari' => 950000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC Digital', 'Audio Premium', 'USB Charger', 'Kursi Nyaman', 'Bagasi Luas']),
                'foto' => 'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800',
            ],
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Toyota Innova Venturer',
                'plat_nomor' => 'EB 6789 AB',
                'jenis' => 'mpv_premium',
                'vehicle_type' => 'Toyota Innova Venturer',
                'brand' => 'Toyota',
                'transmission' => 'automatic',
                'capacity' => 7,
                'year' => 2022,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 900000,
                'harga_sewa_dengan_sopir_per_hari' => 1050000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC Digital', 'Audio Premium', 'USB Charger', 'Kursi Premium', 'Sunroof']),
                'foto' => 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800',
            ],
            // SUV untuk medan Flores yang berbukit
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Toyota Fortuner',
                'plat_nomor' => 'EB 7890 AB',
                'jenis' => 'suv',
                'vehicle_type' => 'Toyota Fortuner',
                'brand' => 'Toyota',
                'transmission' => 'automatic',
                'capacity' => 7,
                'year' => 2022,
                'fuel_type' => 'diesel',
                'harga_sewa_tanpa_sopir_per_hari' => 1200000,
                'harga_sewa_dengan_sopir_per_hari' => 1350000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['4x4', 'AC Digital', 'Audio Premium', 'USB Charger', 'Suspension Tangguh']),
                'foto' => 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',
            ],
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Mitsubishi Pajero',
                'plat_nomor' => 'EB 8901 AB',
                'jenis' => 'suv',
                'vehicle_type' => 'Mitsubishi Pajero',
                'brand' => 'Mitsubishi',
                'transmission' => 'automatic',
                'capacity' => 7,
                'year' => 2021,
                'fuel_type' => 'diesel',
                'harga_sewa_tanpa_sopir_per_hari' => 1100000,
                'harga_sewa_dengan_sopir_per_hari' => 1250000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['4x4', 'AC Digital', 'Audio Premium', 'Suspension Tangguh']),
                'foto' => 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
            ],
            // Minibus untuk travel antar kota Flores
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Toyota Hiace Premio',
                'plat_nomor' => 'EB 9012 AB',
                'jenis' => 'minibus',
                'vehicle_type' => 'Toyota Hiace Premio',
                'brand' => 'Toyota',
                'transmission' => 'manual',
                'capacity' => 15,
                'year' => 2023,
                'fuel_type' => 'diesel',
                'harga_sewa_tanpa_sopir_per_hari' => 1500000,
                'harga_sewa_dengan_sopir_per_hari' => 1650000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio', 'USB Charger', 'Kursi Travel', 'Bagasi Atas']),
                'foto' => 'https://images.unsplash.com/photo-1557223562-6c77ef16210f?w=800',
            ],
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Toyota Hiace Commuter',
                'plat_nomor' => 'EB 0123 AB',
                'jenis' => 'minibus',
                'vehicle_type' => 'Toyota Hiace Commuter',
                'brand' => 'Toyota',
                'transmission' => 'manual',
                'capacity' => 14,
                'year' => 2022,
                'fuel_type' => 'diesel',
                'harga_sewa_tanpa_sopir_per_hari' => 1400000,
                'harga_sewa_dengan_sopir_per_hari' => 1550000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio', 'Kursi Travel', 'Bagasi']),
                'foto' => 'https://images.unsplash.com/photo-1550355424-4b9b00e2aa54?w=800',
            ],
            // Mobil Kecil Lainnya
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Honda Brio',
                'plat_nomor' => 'EB 1234 CD',
                'jenis' => 'city_car',
                'vehicle_type' => 'Honda Brio',
                'brand' => 'Honda',
                'transmission' => 'manual',
                'capacity' => 4,
                'year' => 2022,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 400000,
                'harga_sewa_dengan_sopir_per_hari' => 550000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio']),
                'foto' => 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=800',
            ],
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Honda Jazz',
                'plat_nomor' => 'EB 2345 CD',
                'jenis' => 'city_car',
                'vehicle_type' => 'Honda Jazz',
                'brand' => 'Honda',
                'transmission' => 'automatic',
                'capacity' => 5,
                'year' => 2021,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 450000,
                'harga_sewa_dengan_sopir_per_hari' => 600000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio', 'USB Charger']),
                'foto' => 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800',
            ],
            // Mobil Keluarga Lainnya
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Suzuki Ertiga',
                'plat_nomor' => 'EB 3456 CD',
                'jenis' => 'mpv',
                'vehicle_type' => 'Suzuki Ertiga',
                'brand' => 'Suzuki',
                'transmission' => 'manual',
                'capacity' => 7,
                'year' => 2022,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 450000,
                'harga_sewa_dengan_sopir_per_hari' => 600000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio', 'Bagasi']),
                'foto' => 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800',
            ],
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Honda Mobilio',
                'plat_nomor' => 'EB 4567 CD',
                'jenis' => 'mpv',
                'vehicle_type' => 'Honda Mobilio',
                'brand' => 'Honda',
                'transmission' => 'manual',
                'capacity' => 7,
                'year' => 2021,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 450000,
                'harga_sewa_dengan_sopir_per_hari' => 600000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio', 'Bagasi']),
                'foto' => 'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800',
            ],
            // SUV Lainnya
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Toyota Rush',
                'plat_nomor' => 'EB 5678 CD',
                'jenis' => 'suv',
                'vehicle_type' => 'Toyota Rush',
                'brand' => 'Toyota',
                'transmission' => 'automatic',
                'capacity' => 7,
                'year' => 2022,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 600000,
                'harga_sewa_dengan_sopir_per_hari' => 750000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio', 'USB Charger', 'Suspension Nyaman']),
                'foto' => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
            ],
            [
                'mitra_id' => $mitra->id,
                'nama' => 'Daihatsu Terios',
                'plat_nomor' => 'EB 6789 CD',
                'jenis' => 'suv',
                'vehicle_type' => 'Daihatsu Terios',
                'brand' => 'Daihatsu',
                'transmission' => 'automatic',
                'capacity' => 7,
                'year' => 2021,
                'fuel_type' => 'bensin',
                'harga_sewa_tanpa_sopir_per_hari' => 550000,
                'harga_sewa_dengan_sopir_per_hari' => 700000,
                'tarif_sopir_harian' => 150000,
                'status' => 'tersedia',
                'is_approved' => true,
                'features' => json_encode(['AC', 'Audio', 'Suspension Nyaman']),
                'foto' => 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=800',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            DB::table('vehicles')->insert([
                'mitra_id' => $vehicle['mitra_id'],
                'nama' => $vehicle['nama'],
                'plat_nomor' => $vehicle['plat_nomor'],
                'jenis' => $vehicle['jenis'],
                'vehicle_type' => $vehicle['vehicle_type'],
                'brand' => $vehicle['brand'],
                'transmission' => $vehicle['transmission'],
                'capacity' => $vehicle['capacity'],
                'year' => $vehicle['year'],
                'fuel_type' => $vehicle['fuel_type'],
                'harga_sewa_tanpa_sopir_per_hari' => $vehicle['harga_sewa_tanpa_sopir_per_hari'],
                'harga_sewa_dengan_sopir_per_hari' => $vehicle['harga_sewa_dengan_sopir_per_hari'],
                'tarif_sopir_harian' => $vehicle['tarif_sopir_harian'],
                'status' => $vehicle['status'],
                'is_approved' => $vehicle['is_approved'],
                'features' => $vehicle['features'],
                'foto' => $vehicle['foto'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('Flores vehicles seeder completed successfully! Added ' . count($vehicles) . ' vehicles.');
    }
}